### PR TITLE
Update to 0.147.3

### PR DESCRIPTION
**Pull request by kohanis**
Update to new game version with injection modification

### CODE REVIEW

**Comment by kohanis** [comment]
Love github. There was nothing)

**Comment by AlexMog** [comment]
YaY, classic github problems !
Thanks for your PR, i'll test it in local then I'll merge it :)

**Comment by DiaAWAY** [comment]
Tested the code changes on my server and worked fine :D

~~Quick question; why are the assembly files _lib/assembly_utils.dll_ and _lib/assembly_valheim.dll_ apparently included in the commit? 
No modification seems to have occured, is this just clutter?~~
edit: steam lib files

**Comment by kohanis** [comment]
It's new, just binary. And I have absolutely no idea why github says it's empty in changes)

**Comment by AlexMog** [comment]
Merging it, thanks for your PR !

**Pull request merged**
